
CREATE TABLE IF NOT EXISTS users(
	uid SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags(
	tid SERIAL NOT NULL PRIMARY KEY,
	tag TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS notes (
	note_id SERIAL PRIMARY KEY,
	time VARCHAR(50) NOT NULL ,
	title VARCHAR(30) NOT NULL ,
	description text,
	tid INTEGER,
	uid INTEGER,
	FOREIGN KEY (tid) REFERENCES tags (tid),
	FOREIGN KEY (uid) REFERENCES users (uid)
);

