
CREATE TABLE users(
uid SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
uname VARCHAR(60) NOT NULL UNIQUE,
email TEXT NOT NULL UNIQUE,
password TEXT NOT NULL);

CREATE TABLE notes(
nid SERIAL PRIMARY KEY,
title TEXT NOT NULL,
time DATE NOT NULL,
description TEXT,
tag TEXT,
uid INTEGER NOT NULL);